# Generated by Django 2.0.2 on 2018-02-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koinplus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='koin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kur',
            name='kur_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
