# Generated by Django 2.0.2 on 2018-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koinplus_app', '0003_auto_20180403_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='kur',
            name='kur_count',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
