# Generated by Django 2.0.2 on 2018-04-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koinplus_app', '0004_kur_kur_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kur',
            name='kur_count',
        ),
    ]
